services:
  kaktusgame-frontend:
    restart: always
    build: ../kaktusgame/.
    ports:
      - "${FRONTEND_PORT}:3000"
    
  kaktusgame-backend:
    restart: always
    build: ../api/.
    ports:
      - "${BACKEND_PORT}:5000"