services:
  kaktusgame-frontend:
    restart: always
    build: ../Frontend/.
    ports:
      - "${FRONTEND_PORT}:3000"
    
  kaktusgame-backend:
    restart: always
    build: ../Backend/.
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - TOKEN=${TOKEN}
      - URL=${URL}