version: '3.8'
services:
  kaktusgame-frontend:
    restart: always
    build: ../kaktusgame/.
    ports:
      - "1549:3000"
    
  kaktusgame-backend:
    restart: always
    build: ../api/.
    ports:
      - "1548:5000"